version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: educore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: educore
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: educore-pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@educore.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: educore-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    volumes:
      - ./data/mssql:/var/opt/mssql
